"""empty message

Revision ID: 759ddb3c1e11
Revises: 9102185e79ae
Create Date: 2020-04-28 20:29:40.547964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759ddb3c1e11'
down_revision = '9102185e79ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('precioCompra', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['Producto.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['Producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('precioVenta', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['Producto.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ventas')
    op.drop_table('Inventario')
    op.drop_table('Compras')
    # ### end Alembic commands ###
