"""empty message

Revision ID: 78b65bf25e63
Revises: ca631588135c
Create Date: 2020-04-17 13:35:38.739384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b65bf25e63'
down_revision = 'ca631588135c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Producto', sa.Column('nombre_producto', sa.String(length=150), nullable=True))
    op.drop_column('Producto', 'nombre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Producto', sa.Column('nombre', sa.VARCHAR(length=150), nullable=True))
    op.drop_column('Producto', 'nombre_producto')
    # ### end Alembic commands ###
