"""empty message

Revision ID: 9102185e79ae
Revises: fbbff118a05f
Create Date: 2020-04-26 15:37:42.256124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9102185e79ae'
down_revision = 'fbbff118a05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.alter_column('marca',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('nombre_producto',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('precioCompra',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('precioVentaBase',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('proveedor',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.alter_column('proveedor',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('precioVentaBase',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('precioCompra',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('nombre_producto',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('marca',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
