"""empty message

Revision ID: ca631588135c
Revises: 44e0190273c6
Create Date: 2020-04-17 13:27:01.272878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca631588135c'
down_revision = '44e0190273c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('marca', sa.String(length=150), nullable=True),
    sa.Column('precioVentaBase', sa.Float(), nullable=True),
    sa.Column('precioCompra', sa.Float(), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Producto')
    # ### end Alembic commands ###
