"""empty message

Revision ID: fbbff118a05f
Revises: 
Create Date: 2020-04-17 17:23:43.680732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbff118a05f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=150), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('marca', sa.String(length=150), nullable=True),
    sa.Column('precioVentaBase', sa.Float(), nullable=True),
    sa.Column('precioCompra', sa.Float(), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=True),
    sa.Column('nombre_usuario', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contrasenia', sa.String(length=128), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Usuarios')
    op.drop_table('Producto')
    # ### end Alembic commands ###
