"""Iniciar migraciones

Revision ID: 8cbb11d7ee01
Revises: 
Create Date: 2020-06-09 17:03:33.033754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbb11d7ee01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('precioVentaBase', sa.Float(), nullable=False),
    sa.Column('precioCompra', sa.Float(), nullable=False),
    sa.Column('proveedor', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Producto')),
    sa.UniqueConstraint('nombre_producto', name=op.f('uq_Producto_nombre_producto'))
    )
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Roles')),
    sa.UniqueConstraint('nombre', name=op.f('uq_Roles_nombre'))
    )
    op.create_table('TicketCompras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TicketCompras'))
    )
    op.create_table('TicketVentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TicketVentas'))
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=True),
    sa.Column('nombre_usuario', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contrasenia', sa.String(length=128), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Usuarios')),
    sa.UniqueConstraint('nombre_usuario', name=op.f('uq_Usuarios_nombre_usuario'))
    )
    op.create_table('Compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('precioCompra', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['Producto.id'], name=op.f('fk_Compras_id_producto_Producto')),
    sa.ForeignKeyConstraint(['id_ticket'], ['TicketCompras.id'], name=op.f('fk_Compras_id_ticket_TicketCompras')),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], name=op.f('fk_Compras_id_usuario_Usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Compras'))
    )
    op.create_table('Inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['Producto.id'], name=op.f('fk_Inventario_id_producto_Producto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Inventario'))
    )
    op.create_table('Ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('precioVenta', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['Producto.id'], name=op.f('fk_Ventas_id_producto_Producto')),
    sa.ForeignKeyConstraint(['id_ticket'], ['TicketVentas.id'], name=op.f('fk_Ventas_id_ticket_TicketVentas')),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], name=op.f('fk_Ventas_id_usuario_Usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Ventas'))
    )
    op.create_table('roles_usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['Roles.id'], name=op.f('fk_roles_usuarios_rol_id_Roles')),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuarios.id'], name=op.f('fk_roles_usuarios_usuario_id_Usuarios'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_usuarios')
    op.drop_table('Ventas')
    op.drop_table('Inventario')
    op.drop_table('Compras')
    op.drop_table('Usuarios')
    op.drop_table('TicketVentas')
    op.drop_table('TicketCompras')
    op.drop_table('Roles')
    op.drop_table('Producto')
    # ### end Alembic commands ###
