"""empty message

Revision ID: 9a14f933f9d7
Revises: 759ddb3c1e11
Create Date: 2020-05-01 13:33:16.202073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a14f933f9d7'
down_revision = '759ddb3c1e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.create_unique_constraint('Producto-constraint-unique', ['nombre_producto'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.drop_constraint('Producto-constraint-unique', type_='unique')

    # ### end Alembic commands ###
