"""Agregar tickets a compras y ventas

Revision ID: aa01807d698e
Revises: 2d3891ee346f
Create Date: 2020-06-07 13:26:36.474715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa01807d698e'
down_revision = '2d3891ee346f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ticket', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Compras_id_ticket_TicketCompras'), 'TicketCompras', ['id_ticket'], ['id'])

    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Producto_nombre_producto'), ['nombre_producto'])
        batch_op.drop_constraint('Producto-constraint-unique', type_='unique')

    with op.batch_alter_table('Roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Roles_nombre'), ['nombre'])

    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Usuarios_nombre_usuario'), ['nombre_usuario'])

    with op.batch_alter_table('Ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ticket', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Ventas_id_ticket_TicketVentas'), 'TicketVentas', ['id_ticket'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ventas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Ventas_id_ticket_TicketVentas'), type_='foreignkey')
        batch_op.drop_column('id_ticket')

    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Usuarios_nombre_usuario'), type_='unique')

    with op.batch_alter_table('Roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Roles_nombre'), type_='unique')

    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.create_unique_constraint('Producto-constraint-unique', ['nombre_producto'])
        batch_op.drop_constraint(batch_op.f('uq_Producto_nombre_producto'), type_='unique')

    with op.batch_alter_table('Compras', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Compras_id_ticket_TicketCompras'), type_='foreignkey')
        batch_op.drop_column('id_ticket')

    # ### end Alembic commands ###
