"""empty message

Revision ID: d166abd9d023
Revises: 9a14f933f9d7
Create Date: 2020-05-03 14:15:27.338458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd166abd9d023'
down_revision = '9a14f933f9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket', sa.Integer(), nullable=False, default='1', server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ventas', schema=None) as batch_op:
        batch_op.drop_column('ticket')

    # ### end Alembic commands ###
