"""empty message

Revision ID: d44291904cc8
Revises: d166abd9d023
Create Date: 2020-05-22 01:01:19.593937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44291904cc8'
down_revision = 'd166abd9d023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ventas', schema=None) as batch_op:
        batch_op.drop_column('ticket')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    # ### end Alembic commands ###
